http:
  middlewares:
    www-remover:
       redirectregex:
         regex: ^https://www\.(.*)
         replacement: https://$1
         permanent: true

     http-www-remover:
       redirectregex:
         regex: ^http://www\.(.*)
         replacement: https://$1
         permanent: true

    auth:
      basicAuth:
        users:
          - "login:basic-auth-hash"

  routers:
    http-www-router:
      rule: HostRegexp(`{host:www\..+}`)
      service: noop@internal
      middlewares:
         - http-www-remover

    www-router:
      rule: HostRegexp(`{host:www\..+}`)
      service: noop@internal
      tls: true
      middlewares:
         - www-remover

    dashboard:
      rule: Host(`traefik.your-site.com`)
      service: api@internal
      middlewares:
        - auth
      
tls:
  options:
    default:
      sniStrict: true