log:
  level: ERROR

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  pgadmin:
    address: :8081
  traefik:
    address: :8080

certificatesresolvers:
  myresolver:
    acme:
      email: itartpro@gmail.com
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare

api:
  dashboard: true
